spring.cloud.stream:
  bindings:
    order-event-outbound:
      destination: sale-event-topic
  default-binder: kafka
  kafka.binder:
    configuration:
      commit.interval.ms: 1000
    brokers: localhost:9092
    serdeError: logAndContinue
  kafka.bindings:
    order-event-outbound:
      producer:
        configuration:
          default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
          spring.json.trusted.packages: '*'
          spring.json.value.default.type: